CREATE TABLE `PUSH_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TEXT` varchar(220) COLLATE utf8_bin DEFAULT NULL,
  `URL` varchar(512) COLLATE utf8_bin NOT NULL,
  `TARGET` char(1) COLLATE utf8_bin NOT NULL COMMENT 'B-broadcast;G-group;M-messive;P-point',
  `SEND_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `SEND_BY` varchar(45) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

